import type { Scenario } from "./types";
import { defaultTriageDurationProfile } from "./triageDuration";
import { defaultTimingProfile } from "./timingProfile";

export const defaultScenario: Scenario = {
  id: "scenario-default-evening-flow",
  name: "Single Provider Evening Flow",
  shiftStartMinute: 0,
  shiftDurationMinutes: 240,
  randomSeed: "ed-flow-mvp-001",
  roomCapacity: 8,
  providerCount: 1,
  providerAssignmentMode: "team",
  nurseCount: 2,
  techCount: 1,
  fastTrackEnabled: true,
  triageProviderEnabled: true,
  triageProviderMode: "automated",
  arrivalProfile: [
    { hourOffset: 0, expectedArrivals: 12 },
    { hourOffset: 1, expectedArrivals: 12 },
    { hourOffset: 2, expectedArrivals: 12 },
    { hourOffset: 3, expectedArrivals: 12 },
  ],
  esiDistribution: {
    values: [
      { value: 2, weight: 15 },
      { value: 3, weight: 45 },
      { value: 4, weight: 30 },
      { value: 5, weight: 10 },
    ],
  },
  complaintDistribution: {
    values: [
      { value: "suspected_acs", weight: 5 },
      { value: "chest_pain", weight: 18 },
      { value: "abdominal_pain", weight: 16 },
      { value: "shortness_of_breath", weight: 12 },
      { value: "injury", weight: 15 },
      { value: "weakness_dizziness", weight: 12 },
      { value: "fever_infection", weight: 12 },
      { value: "behavioral_health", weight: 6 },
      { value: "stroke_neuro", weight: 3 },
      { value: "sepsis_concern", weight: 3 },
      { value: "major_trauma", weight: 2 },
      { value: "pediatric", weight: 5 },
      { value: "ob_pregnancy", weight: 3 },
      { value: "syncope", weight: 5 },
      { value: "altered_mental_status", weight: 3 },
      { value: "overdose_intoxication", weight: 3 },
      { value: "renal_urinary", weight: 6 },
      { value: "gi_bleed", weight: 3 },
      { value: "allergic_reaction", weight: 3 },
      { value: "burn", weight: 2 },
      { value: "eye_ent", weight: 4 },
      { value: "back_pain", weight: 5 },
      { value: "hypertensive_symptoms", weight: 3 },
      { value: "diabetic_emergency", weight: 3 },
      { value: "social_placement", weight: 3 },
      { value: "minor_complaint", weight: 8 },
    ],
  },
  workupDistribution: {
    values: [
      { value: "none", weight: 10 },
      { value: "basic_labs", weight: 30 },
      { value: "labs_imaging", weight: 30 },
      { value: "cardiac", weight: 15 },
      { value: "complex", weight: 15 },
    ],
  },
  patientMix: {
    acuity: "standard",
    admission: "standard",
    complaint: "balanced",
    seed: 1,
    workup: "standard",
  },
  workflowTimingProfile: {
    acsDoorToEcgTargetMinutes: 8,
    deteriorationGraceMinutes: 30,
    repeatTroponinDelayMinutes: 60,
    sepsisAntibioticsMinutes: 35,
    sepsisBloodCultureMinutes: 8,
    sepsisCriticalWaitMinutes: 10,
    sepsisFluidsMinutes: 20,
    sepsisLactateCollectionMinutes: 5,
    stemiDoorToEcgTargetMinutes: 5,
  },
  coachPriorityProfile: {
    mode: "balanced",
    acuityWeight: 1000,
    riskWeight: 150,
    waitWeight: 1,
  },
  coachStrategyPriorityProfiles: {
    front_end_focus: {
      mode: "front_end",
      acuityWeight: 750,
      riskWeight: 125,
      waitWeight: 1,
    },
    middle_flow_focus: {
      mode: "balanced",
      acuityWeight: 1000,
      riskWeight: 150,
      waitWeight: 1,
    },
    disposition_focus: {
      mode: "throughput",
      acuityWeight: 700,
      riskWeight: 100,
      waitWeight: 2,
    },
    resource_aware: {
      mode: "balanced",
      acuityWeight: 900,
      riskWeight: 125,
      waitWeight: 1,
    },
    safety_first: {
      mode: "safety_first",
      acuityWeight: 1200,
      riskWeight: 300,
      waitWeight: 1,
    },
    fast_track: {
      mode: "throughput",
      acuityWeight: 450,
      riskWeight: 75,
      waitWeight: 1,
    },
    balanced_operations: {
      mode: "balanced",
      acuityWeight: 1000,
      riskWeight: 150,
      waitWeight: 1,
    },
  },
  triageDurationProfile: defaultTriageDurationProfile,
  triageDurationMultiplier: 1,
  timingProfile: defaultTimingProfile,
  boardingProfile: {
    enabled: true,
    admitBoardingDelayMin: 35,
    admitBoardingDelayMax: 90,
  },
  lwbsProfile: {
    enabled: false,
    minimumWaitBeforeLWBS: 90,
    lowPatienceMultiplier: 1.6,
    mediumPatienceMultiplier: 1,
    highPatienceMultiplier: 0.45,
    highAcuityBlockedEsiLevels: [1, 2],
  },
  minimumStemiAlertPatients: 1,
};
